# Generated by Django 3.2 on 2021-07-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KNIT_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default='', max_length=10)),
                ('catagory', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='KNIT_App/image')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
