# Generated by Django 3.2 on 2021-07-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KNIT_app', '0005_auto_20210705_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='form',
            name='img',
        ),
        migrations.AlterField(
            model_name='form',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
